# Generated by Django 5.0.3 on 2024-03-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0002_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='product',
            new_name='product_id',
        ),
    ]
